services:
  server:
    build: .
    volumes:
      - ./var:/app/var
    command: ./mysql-detector web 8000 

  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
